export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_ACTIVE_EVENT = 'SET_ACTIVE_EVENT'
export const SET_MY_EVENTS = 'SET_MY_EVENTS'